baseURL = "https://blog.pluser.net/"
languageCode = "ja"
title = "かすれた*Pluser*の巻物"
theme = "emacsy"
DefaultContentLanguage = "ja"
hasCJKLanguage = true
pygmentsUseClasses = true
pygmentsCodeFences = true
