baseURL = "https://blog.pluser.net/"
languageCode = "ja"
title = "かすれた*Pluser*の巻物"
theme = "emacsy"
DefaultContentLanguage = "ja"
hasCJKLanguage = true
pygmentsStyle = "dracura"
pygmentsCodeFences = true
pygmentsOptions = "linenos=true"


[outputs]
home = ["HTML", "Atom"]

disableKinds = ['RSS']
