baseURL = "https://blog.pluser.net"
#languageCode = "ja"
theme = "emacsy"
DefaultContentLanguage = "ja"
hasCJKLanguage = true
googleAnalytics = "UA-582650-9"
enableGitInfo = true

[markup]
[markup.highlight]
anchorLineNos = true
codeFences = true
lineNos = false
lineNumbersInTable = false

[outputs]
home = ["HTML", "Atom"]
disableKinds = ['RSS']

[languages]
[languages.ja]
title = "かすれた*Pluser*の巻物"
[languages.en]
title = "Faint Scroll of *Pluser*"