baseURL = "https://blog.pluser.net"
#languageCode = "ja"
theme = "emacsy"
DefaultContentLanguage = "ja"
hasCJKLanguage = true
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsOptions = "linenos=table"
googleAnalytics = "UA-582650-9"

[outputs]
home = ["HTML", "Atom"]

disableKinds = ['RSS']

[languages]
[languages.ja]
title = "かすれた*Pluser*の巻物"
[languages.en]
title = "Faint Scroll of *Pluser*"